### ISSUE TITLE
ovladani zvuku

### ISSUE THREAD

**Issue by miroslavchmelka** [gameeapp/gamee-js#1]
pridat moznost vypnout / zapnout zvuk u hry

**Comment by morihladko** [comment]
Pridal som 

### `gamee.gameMute()`

Ohlasi gamee, ze chce vypnut zvuk.

### `gamee.gameUnmute()`

Ohlasi gamee, ze chce zapnut zvuk.

## Implementacia 

Nativna appka bude pocuvat na zmeny v url **`gamee://mute/(true|false)`** kde `true` ak chceme vypnut, `false` ak chceme zapnut.

Webova appka bude odchytavat postMesasge snazvom `'mute'` a parametrom `true|false`.

Komitol som to do branche https://github.com/gameeapp/gamee-js/tree/3-request-social-data

**Comment by miroslavchmelka** [comment]
ale ono by to melo spis fungovat opacne => aplikace ohlasi hre, aby vypnula zvuky. My je totiz nedokazeme vypnout z aplikace

**Comment by morihladko** [comment]
ok revertol som povodne a pushol pozadovane upravy (tj pridal onUnmute, po zmergovani mozem vygenerovat dokumentaciu v gh-pages vetve

**Comment by miroslavchmelka** [comment]
Tak to prosím mergni a přidej tu dokumentaci
V rámci zpětné kompatibility to nic nemůže ohrozit, ne?

**Comment by morihladko** [comment]
nemalo by
