### ISSUE TITLE
Controller stopped working in 2.0.2

### ISSUE THREAD

**Issue by spixy** [gameeapp/gamee-js#12]
Hi, from gameInit("OneButton",...) it throws 
> wrapKeyEvent is not defined

You can try it [here](https://www-devel.gameeapp.com/game/IGBrpztD)

**Comment by EntityB** [comment]
I will take a look today! Thx

**Comment by EntityB** [comment]
I replicated the bug. But there was no problem in the code. It seems that my webpack module was broken. So did cleanup and rebuild and it seems to work. 

Here is the new release. It should be fixed now. 
https://github.com/gameeapp/gamee-js/releases/tag/v2.0.3

Let me know if you have any other issues ;)
