### ISSUE TITLE
requestSocial avatars

### ISSUE THREAD

**Issue by spixy** [gameeapp/gamee-js#13]
When should I call **requestSocial** method?
After first run the callback returns me friends (some of them or all), with missing avatars.
But if I call **requestSocial** for second time, then all friends have avatars.

**Comment by EntityB** [comment]
Android app? iOS app? Device? or emulator?

**Comment by spixy** [comment]
android

**Comment by EntityB** [comment]
Thx we are on it!

**Comment by spixy** [comment]
and `requestSocial ` returns only friends with higher score than my highScore.
Is it a bug or feature? :)

**Comment by EntityB** [comment]
It should currently return 5 friends with higher score than yours. It is a feature. 

We want to change the pattern somehow :)

**Comment by spixy** [comment]
ok, thanks :)
