### ISSUE TITLE
bug u touch her

### ISSUE THREAD

**Issue by miroslavchmelka** [gameeapp/gamee-js#2]
nemaji ted zadny controller a nefunguji tam dobre udalosti

**Comment by morihladko** [comment]
no skusil som arkanoid bez controllera http://goo.gl/TwmIbf (klikni na start) a eventy sa posielaju (vid konzolu) .. o ake konkretne udalosti sa jedna? 

moze byt este chyba v implementacii v mobilnaj appke, testoval som to len na webe, ale z kodu na mna nic nekricalo, preco by malo vadit, ze sa nezavolal requestController

**Comment by NokFrt** [comment]
Uz si ten problem detailne nepamatuji, ale tohle jsem zjistil, kdyz jsem na to narazil:

Pokud hra nepouziva zadny controller a gamee.gameStart() volam az po obdrzeni prvni touch udalosti, tak se to chova tak, jako kdybych to gamee.gameStart() vubec nezavolal (nahore v aplikaci se nezmeni tlacitka). Pokud gamee.gameLoaded() vynecham a hned po nacteni hry volam gamee.gameStart() tak to funguje. Ve hrach co maji controller tenhle problem neni - je to videt napr. ted v tom Hamster Fly, kde se gamee.gameStart() zavola az po vyberu startovniho uhlu.

**Comment by morihladko** [comment]
hmm a je to na iOS ci i na Androide? pride mi to ze to moze byt nejakou vlastnostou webviewu v nativnej appke, ako som pisal vo web appke to nema preco nefungovat

**Comment by morihladko** [comment]
ok, po debuggovani v Androide som zistil, ze detekcia zmeny url, ktoru pouzivame na komunikaciu hra -> nativna appka potrebuje delay, teda, pri tych touch hrach sa vola asi gameLoaded a gameStarted hned za sebou, url sa 2x zmeni ale android to iba 1x zdetekoval, na tu poslednu

FIX by som zriesil pridat 100 ms delay, otazka je ci nebude vadit

nepametam si presne, ale ma byt asi gameLoaded prvy a potom gameStart?

**Comment by miroslavchmelka** [comment]
Prvně gameloaded a až pak gamestart
Dne 13. 12. 2015 19:44 napsal uživatel "Peter Morihladko" <
notifications@github.com>:

**Comment by EntityB** [comment]
deprecated
