### ISSUE TITLE
pridat moznost predat hre informace o hracich

### ISSUE THREAD

**Issue by miroslavchmelka** [gameeapp/gamee-js#3]
mobilni aplikace by ji poslala neco jako pole v jsonu, kde by bylo (id, jmeno, nickname, skore, URL obrazku) => takto treba 5 lidi

pokud by to hra podporovala, tak by to pak mohla ukazovat => treba, kdyz by byla hra ve skoku do dalky, tak by se tam mohly ukazat obliceje useru a hned bys videl, jak jsi skocil (koho jsi prekonal atd.)

**Comment by morihladko** [comment]
No ja by som to navrhol takto

### `gamee.requestSocialData`
Tuto funkciu by volali hry, ziskali by tym objekt s datami format napr.
```javascript
{
  'friends': [
    {
      'name': 'User 1',
      'avatar': 'http://gravatar.com/xyz.png'
      'highscore': 222
    }
  ]
}
```

Mobilne appky by tento objekt nastavili ako **`window.$$gameeSocialData`**, pri webovom by sa to poslalo cez window.postMessage

Taktiez by mohla hra dostavat i realtime updaty nejaky `gamee.onSocialUpdate = function(data) {}`

Komitol som to do branche https://github.com/gameeapp/gamee-js/tree/3-request-social-data

**Comment by miroslavchmelka** [comment]
tohle taky mergni a dopln do dokumentace

**Comment by EntityB** [comment]
Deprecated
